### ISSUE TITLE
Can not find "rodrigues()" function

### ISSUE THREAD

**Issue by zengbw** [christianwengert/calib_toolbox_addon#1]
Hi,
   I try to use the calibration code, but I occurred the error " undefined function or variables 'rodrigues' ". And from the handeye.m, we know that it should be a function, but it didn't in the calib_toolbox_addon. Could you please help to add the function 'rodrigues' to the toolbox? Thank you!

**Comment by christianwengert** [comment]
This file is in the calibration toolbox

http://www.vision.caltech.edu/bouguetj/calib_doc/download/index.html

This package is an addon and relies on above code
